//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintsCapture.Ui.Language {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintsCapture.Ui.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept *.
        /// </summary>
        public static string AcceptStar {
            get {
                return ResourceManager.GetString("AcceptStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print capture application.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Capture.
        /// </summary>
        public static string CaptureEnd {
            get {
                return ResourceManager.GetString("CaptureEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In case of errors, rescan or override prints. Press &quot;End&quot; when done..
        /// </summary>
        public static string CaptureEndInstruction {
            get {
                return ResourceManager.GetString("CaptureEndInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture Endorsement Finger.
        /// </summary>
        public static string CaptureEndorsement {
            get {
                return ResourceManager.GetString("CaptureEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flats only.
        /// </summary>
        public static string CaptureFlatOnly {
            get {
                return ResourceManager.GetString("CaptureFlatOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture Mode.
        /// </summary>
        public static string CaptureMode {
            get {
                return ResourceManager.GetString("CaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flats and rolled.
        /// </summary>
        public static string CaptureStandard14 {
            get {
                return ResourceManager.GetString("CaptureStandard14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flats, rolled and palms.
        /// </summary>
        public static string CaptureStandardAndPalm {
            get {
                return ResourceManager.GetString("CaptureStandardAndPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan.
        /// </summary>
        public static string CaptureStart {
            get {
                return ResourceManager.GetString("CaptureStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flag missing prints and press &quot;Scan&quot; button to start..
        /// </summary>
        public static string CaptureStartInstruction {
            get {
                return ResourceManager.GetString("CaptureStartInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CardScan.
        /// </summary>
        public static string CardScan {
            get {
                return ResourceManager.GetString("CardScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Application.
        /// </summary>
        public static string CloseApplicationTitle {
            get {
                return ResourceManager.GetString("CloseApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print session will end. No print will be saved..
        /// </summary>
        public static string CloseConfirmationPrompt {
            get {
                return ResourceManager.GetString("CloseConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compression :.
        /// </summary>
        public static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consent Text.
        /// </summary>
        public static string ConsentText {
            get {
                return ResourceManager.GetString("ConsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot continue. Some errors must be corrected..
        /// </summary>
        public static string CorrectErrorBeforeContinue {
            get {
                return ResourceManager.GetString("CorrectErrorBeforeContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not set device information on service..
        /// </summary>
        public static string CouldNotSetDeviceInformation {
            get {
                return ResourceManager.GetString("CouldNotSetDeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Device.
        /// </summary>
        public static string CurrentDevice {
            get {
                return ResourceManager.GetString("CurrentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom order file is invalid.
        /// </summary>
        public static string CustomOrderFileInvalid {
            get {
                return ResourceManager.GetString("CustomOrderFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Using custom capture order.
        /// </summary>
        public static string CustomOrderUsed {
            get {
                return ResourceManager.GetString("CustomOrderUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data compression :.
        /// </summary>
        public static string DataCompressionLabel {
            get {
                return ResourceManager.GetString("DataCompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yyyy-mm-dd.
        /// </summary>
        public static string DateFormatHelper {
            get {
                return ResourceManager.GetString("DateFormatHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a date.
        /// </summary>
        public static string DatePickerWatermark {
            get {
                return ResourceManager.GetString("DatePickerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define override.
        /// </summary>
        public static string DefineOverride {
            get {
                return ResourceManager.GetString("DefineOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dpi :.
        /// </summary>
        public static string DpiDescriptionLabel {
            get {
                return ResourceManager.GetString("DpiDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string EditPrint {
            get {
                return ResourceManager.GetString("EditPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable sequence check.
        /// </summary>
        public static string EnableSequenceCheck {
            get {
                return ResourceManager.GetString("EnableSequenceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The print session will end. The prints will be saved..
        /// </summary>
        public static string EndConfirmationPrompt {
            get {
                return ResourceManager.GetString("EndConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is the english endorsement text..
        /// </summary>
        public static string EndorsementConsentText {
            get {
                return ResourceManager.GetString("EndorsementConsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endorsement consent text for third party.
        /// </summary>
        public static string EndorsementConsentWindowTitle {
            get {
                return ResourceManager.GetString("EndorsementConsentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endorsement Finger.
        /// </summary>
        public static string EndorsementFinger {
            get {
                return ResourceManager.GetString("EndorsementFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ({1}).
        /// </summary>
        public static string EndorsementNamePattern {
            get {
                return ResourceManager.GetString("EndorsementNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The print session will end. No endorsement finger was captured. The prints will be saved..
        /// </summary>
        public static string EndorsementNotSetPrompt {
            get {
                return ResourceManager.GetString("EndorsementNotSetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endorsement.
        /// </summary>
        public static string EndorsementTitle {
            get {
                return ResourceManager.GetString("EndorsementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left Hand.
        /// </summary>
        public static string enumHandLeft {
            get {
                return ResourceManager.GetString("enumHandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string enumHandNone {
            get {
                return ResourceManager.GetString("enumHandNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete Palm.
        /// </summary>
        public static string enumHandPartCompletePalm {
            get {
                return ResourceManager.GetString("enumHandPartCompletePalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endorsement.
        /// </summary>
        public static string enumHandPartEndorsement {
            get {
                return ResourceManager.GetString("enumHandPartEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Four Fingers.
        /// </summary>
        public static string enumHandPartFourFlats {
            get {
                return ResourceManager.GetString("enumHandPartFourFlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hypothenar.
        /// </summary>
        public static string enumHandPartHypothenar {
            get {
                return ResourceManager.GetString("enumHandPartHypothenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        public static string enumHandPartIndex {
            get {
                return ResourceManager.GetString("enumHandPartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Little.
        /// </summary>
        public static string enumHandPartLittle {
            get {
                return ResourceManager.GetString("enumHandPartLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lower Palm.
        /// </summary>
        public static string enumHandPartLowerPalm {
            get {
                return ResourceManager.GetString("enumHandPartLowerPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Middle.
        /// </summary>
        public static string enumHandPartMiddle {
            get {
                return ResourceManager.GetString("enumHandPartMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ring.
        /// </summary>
        public static string enumHandPartRing {
            get {
                return ResourceManager.GetString("enumHandPartRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thumb.
        /// </summary>
        public static string enumHandPartThumb {
            get {
                return ResourceManager.GetString("enumHandPartThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two Thumbs.
        /// </summary>
        public static string enumHandPartTwoThumbs {
            get {
                return ResourceManager.GetString("enumHandPartTwoThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UpperPalm.
        /// </summary>
        public static string enumHandPartUpperPalm {
            get {
                return ResourceManager.GetString("enumHandPartUpperPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right Hand.
        /// </summary>
        public static string enumHandRight {
            get {
                return ResourceManager.GetString("enumHandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flat.
        /// </summary>
        public static string enumHandScanKindFlat {
            get {
                return ResourceManager.GetString("enumHandScanKindFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rolled.
        /// </summary>
        public static string enumHandScanKindRolled {
            get {
                return ResourceManager.GetString("enumHandScanKindRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error(s) have been detected. Please rescan :.
        /// </summary>
        public static string ErrorHaveBeenDetected {
            get {
                return ResourceManager.GetString("ErrorHaveBeenDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finger Presence.
        /// </summary>
        public static string FingerPresenceWindowTitle {
            get {
                return ResourceManager.GetString("FingerPresenceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fingers.
        /// </summary>
        public static string Fingers {
            get {
                return ResourceManager.GetString("Fingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Four Fingers.
        /// </summary>
        public static string FourFinger {
            get {
                return ResourceManager.GetString("FourFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bandaged.
        /// </summary>
        public static string HandPartBandaged {
            get {
                return ResourceManager.GetString("HandPartBandaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Foreign Reason.
        /// </summary>
        public static string HandPartForeignReason {
            get {
                return ResourceManager.GetString("HandPartForeignReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing Image.
        /// </summary>
        public static string HandPartMissingImage {
            get {
                return ResourceManager.GetString("HandPartMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Physical Limitations.
        /// </summary>
        public static string HandPartPhysicalLimitation {
            get {
                return ResourceManager.GetString("HandPartPhysicalLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Present.
        /// </summary>
        public static string HandPartPresent {
            get {
                return ResourceManager.GetString("HandPartPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amputated.
        /// </summary>
        public static string HandPatAmputated {
            get {
                return ResourceManager.GetString("HandPatAmputated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Include palm prints.
        /// </summary>
        public static string IncludePalm {
            get {
                return ResourceManager.GetString("IncludePalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text contains invalid characters.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan Preview Window.
        /// </summary>
        public static string LivePreviewTitle {
            get {
                return ResourceManager.GetString("LivePreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LiveScan.
        /// </summary>
        public static string Livescan {
            get {
                return ResourceManager.GetString("Livescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading previous prints. Please wait..
        /// </summary>
        public static string LoadingPreviousPrints {
            get {
                return ResourceManager.GetString("LoadingPreviousPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading prints {0} of {1}.
        /// </summary>
        public static string LoadingPrintsXOfY {
            get {
                return ResourceManager.GetString("LoadingPrintsXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Misc.
        /// </summary>
        public static string MiscOptions {
            get {
                return ResourceManager.GetString("MiscOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date of the missing finger finger contain at least the year and the month..
        /// </summary>
        public static string MissingDateInvalidLenght {
            get {
                return ResourceManager.GetString("MissingDateInvalidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing finger.
        /// </summary>
        public static string MissingFinger {
            get {
                return ResourceManager.GetString("MissingFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing since.
        /// </summary>
        public static string MissingSince {
            get {
                return ResourceManager.GetString("MissingSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print override or missing attribute different on server for {0}..
        /// </summary>
        public static string MsgPrintSyncError {
            get {
                return ResourceManager.GetString("MsgPrintSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print position differs for {0}. Desactivate the position and reactivate it again..
        /// </summary>
        public static string MsgSwapDifferent {
            get {
                return ResourceManager.GetString("MsgSwapDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compression into Wsq failed for {0}. Resend the print..
        /// </summary>
        public static string MsgWsqCompressionFailed {
            get {
                return ResourceManager.GetString("MsgWsqCompressionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Device.
        /// </summary>
        public static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No override.
        /// </summary>
        public static string NoOverride {
            get {
                return ResourceManager.GetString("NoOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No print.
        /// </summary>
        public static string NoPrint {
            get {
                return ResourceManager.GetString("NoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print analyse in progress ....
        /// </summary>
        public static string OperationAnalysis {
            get {
                return ResourceManager.GetString("OperationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print analysis completed.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No print to analyse.
        /// </summary>
        public static string OperationNoPrint {
            get {
                return ResourceManager.GetString("OperationNoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Override options always visible.
        /// </summary>
        public static string OverrideAlwayDisplayed {
            get {
                return ResourceManager.GetString("OverrideAlwayDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable override of flat prints.
        /// </summary>
        public static string OverrideDisableFlat {
            get {
                return ResourceManager.GetString("OverrideDisableFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable override of palm prints.
        /// </summary>
        public static string OverrideDisablePalm {
            get {
                return ResourceManager.GetString("OverrideDisablePalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable override of rolled prints.
        /// </summary>
        public static string OverrideDisableRolled {
            get {
                return ResourceManager.GetString("OverrideDisableRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flats :.
        /// </summary>
        public static string OverrideFlatLabel {
            get {
                return ResourceManager.GetString("OverrideFlatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Override reason cannot be blank. Specify a reason..
        /// </summary>
        public static string OverrideReasonCannotBeBlank {
            get {
                return ResourceManager.GetString("OverrideReasonCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry :.
        /// </summary>
        public static string OverrideRetryNeededLabel {
            get {
                return ResourceManager.GetString("OverrideRetryNeededLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rolled :.
        /// </summary>
        public static string OverrideRolledLabel {
            get {
                return ResourceManager.GetString("OverrideRolledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overrides.
        /// </summary>
        public static string Overrides {
            get {
                return ResourceManager.GetString("Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Palm Quality Control.
        /// </summary>
        public static string PalmQualityControlTitle {
            get {
                return ResourceManager.GetString("PalmQualityControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Palms.
        /// </summary>
        public static string Palms {
            get {
                return ResourceManager.GetString("Palms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ({1}).
        /// </summary>
        public static string PhysicalPartNamePattern {
            get {
                return ResourceManager.GetString("PhysicalPartNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original scanned position was {0}.
        /// </summary>
        public static string PositionChangedFrom {
            get {
                return ResourceManager.GetString("PositionChangedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position attribution :.
        /// </summary>
        public static string PositionEnabledLabel {
            get {
                return ResourceManager.GetString("PositionEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Absence / Presence.
        /// </summary>
        public static string PresenceWindowTitle {
            get {
                return ResourceManager.GetString("PresenceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous print.
        /// </summary>
        public static string PreviousPrint {
            get {
                return ResourceManager.GetString("PreviousPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        public static string PrintFingerIndex {
            get {
                return ResourceManager.GetString("PrintFingerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Little.
        /// </summary>
        public static string PrintFingerLittle {
            get {
                return ResourceManager.GetString("PrintFingerLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Middle.
        /// </summary>
        public static string PrintFingerMiddle {
            get {
                return ResourceManager.GetString("PrintFingerMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ring.
        /// </summary>
        public static string PrintFingerRing {
            get {
                return ResourceManager.GetString("PrintFingerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thumb.
        /// </summary>
        public static string PrintFingerThumb {
            get {
                return ResourceManager.GetString("PrintFingerThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flat.
        /// </summary>
        public static string PrintFlat {
            get {
                return ResourceManager.GetString("PrintFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on image to shrink it&apos;s size..
        /// </summary>
        public static string PrintIsZoomed {
            get {
                return ResourceManager.GetString("PrintIsZoomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left Hand Prints.
        /// </summary>
        public static string PrintLeftHand {
            get {
                return ResourceManager.GetString("PrintLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print could match to {0}. Sequence : {1}.
        /// </summary>
        public static string PrintMatchWarning {
            get {
                return ResourceManager.GetString("PrintMatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ({1}), {2}.
        /// </summary>
        public static string PrintNamePattern {
            get {
                return ResourceManager.GetString("PrintNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Palm.
        /// </summary>
        public static string PrintPalm {
            get {
                return ResourceManager.GetString("PrintPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hypothenar.
        /// </summary>
        public static string PrintPalmHypothenar {
            get {
                return ResourceManager.GetString("PrintPalmHypothenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lower Palm.
        /// </summary>
        public static string PrintPalmLower {
            get {
                return ResourceManager.GetString("PrintPalmLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upper Palm.
        /// </summary>
        public static string PrintPalmUpper {
            get {
                return ResourceManager.GetString("PrintPalmUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print position was changed to {0}.
        /// </summary>
        public static string PrintPositionChangedTo {
            get {
                return ResourceManager.GetString("PrintPositionChangedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad.
        /// </summary>
        public static string PrintQualityBad {
            get {
                return ResourceManager.GetString("PrintQualityBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excellent.
        /// </summary>
        public static string PrintQualityExcellent {
            get {
                return ResourceManager.GetString("PrintQualityExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good.
        /// </summary>
        public static string PrintQualityGood {
            get {
                return ResourceManager.GetString("PrintQualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very Bad.
        /// </summary>
        public static string PrintQualityVeryBad {
            get {
                return ResourceManager.GetString("PrintQualityVeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very Good.
        /// </summary>
        public static string PrintQualityVeryGood {
            get {
                return ResourceManager.GetString("PrintQualityVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right Hand Prints.
        /// </summary>
        public static string PrintRightHand {
            get {
                return ResourceManager.GetString("PrintRightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rolled.
        /// </summary>
        public static string PrintRolled {
            get {
                return ResourceManager.GetString("PrintRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print parts.
        /// </summary>
        public static string PrintSegments {
            get {
                return ResourceManager.GetString("PrintSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print Session.
        /// </summary>
        public static string PrintSession {
            get {
                return ResourceManager.GetString("PrintSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some prints are not ready :.
        /// </summary>
        public static string PrintsNotReady {
            get {
                return ResourceManager.GetString("PrintsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string PrintsStatusOk {
            get {
                return ResourceManager.GetString("PrintsStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print captured more than once..
        /// </summary>
        public static string PrintStatusDouble {
            get {
                return ResourceManager.GetString("PrintStatusDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In error.
        /// </summary>
        public static string PrintStatusInError {
            get {
                return ResourceManager.GetString("PrintStatusInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In error and print position was changed.
        /// </summary>
        public static string PrintStatusInErrorSwapped {
            get {
                return ResourceManager.GetString("PrintStatusInErrorSwapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print is being processed.
        /// </summary>
        public static string PrintStatusInProcess {
            get {
                return ResourceManager.GetString("PrintStatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print is missing.
        /// </summary>
        public static string PrintStatusMissing {
            get {
                return ResourceManager.GetString("PrintStatusMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print not captured.
        /// </summary>
        public static string PrintStatusNotCaptured {
            get {
                return ResourceManager.GetString("PrintStatusNotCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print error was overriden.
        /// </summary>
        public static string PrintStatusOverriden {
            get {
                return ResourceManager.GetString("PrintStatusOverriden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pending evaluation.
        /// </summary>
        public static string PrintStatusPendingEvaluation {
            get {
                return ResourceManager.GetString("PrintStatusPendingEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print is ready.
        /// </summary>
        public static string PrintStatusProcessed {
            get {
                return ResourceManager.GetString("PrintStatusProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print quality is bad.
        /// </summary>
        public static string PrintStatusQualityError {
            get {
                return ResourceManager.GetString("PrintStatusQualityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print Sequence check failed.
        /// </summary>
        public static string PrintStatusSequenceError {
            get {
                return ResourceManager.GetString("PrintStatusSequenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence score was matched to another finger..
        /// </summary>
        public static string PrintStatusSequenceSwappedError {
            get {
                return ResourceManager.GetString("PrintStatusSequenceSwappedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service error.
        /// </summary>
        public static string PrintStatusServiceError {
            get {
                return ResourceManager.GetString("PrintStatusServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submitted.
        /// </summary>
        public static string PrintStatusSubmited {
            get {
                return ResourceManager.GetString("PrintStatusSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Template in error.
        /// </summary>
        public static string PrintStatusTemplateError {
            get {
                return ResourceManager.GetString("PrintStatusTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        public static string PrintStatusUnknown {
            get {
                return ResourceManager.GetString("PrintStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown error.
        /// </summary>
        public static string PrintStatusUnknownError {
            get {
                return ResourceManager.GetString("PrintStatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validated, but print position was changed.
        /// </summary>
        public static string PrintStatusValidatedSwapped {
            get {
                return ResourceManager.GetString("PrintStatusValidatedSwapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print was matched to : {0}.
        /// </summary>
        public static string PrintWasMatchedTo {
            get {
                return ResourceManager.GetString("PrintWasMatchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad quality.
        /// </summary>
        public static string QualityBad {
            get {
                return ResourceManager.GetString("QualityBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality was evaluated.
        /// </summary>
        public static string QualityEvaluated {
            get {
                return ResourceManager.GetString("QualityEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good quality.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality:.
        /// </summary>
        public static string QualityLabel {
            get {
                return ResourceManager.GetString("QualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality : {0}.
        /// </summary>
        public static string QualityScorePattern {
            get {
                return ResourceManager.GetString("QualityScorePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality threshold.
        /// </summary>
        public static string QualityThreshold {
            get {
                return ResourceManager.GetString("QualityThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reposition.
        /// </summary>
        public static string Reposition {
            get {
                return ResourceManager.GetString("Reposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send to Service.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session and all prints will be reseted..
        /// </summary>
        public static string ResetConfirmationPrompt {
            get {
                return ResourceManager.GetString("ResetConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolution : {0}.
        /// </summary>
        public static string ResolutionInfo {
            get {
                return ResourceManager.GetString("ResolutionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolution :.
        /// </summary>
        public static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify Resolution for fingerprints. Configure correctly and try again..
        /// </summary>
        public static string ResolutionNotSet {
            get {
                return ResourceManager.GetString("ResolutionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolutions.
        /// </summary>
        public static string Resolutions {
            get {
                return ResourceManager.GetString("Resolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Service.
        /// </summary>
        public static string RestartService {
            get {
                return ResourceManager.GetString("RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume Capture.
        /// </summary>
        public static string ResumeCapture {
            get {
                return ResourceManager.GetString("ResumeCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Compression DISABLED.
        /// </summary>
        public static string RulesDataCompressionDisabled {
            get {
                return ResourceManager.GetString("RulesDataCompressionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality ENABLED, Threshold:.
        /// </summary>
        public static string RulesQualityEnabled {
            get {
                return ResourceManager.GetString("RulesQualityEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence DISABLED.
        /// </summary>
        public static string RulesSequenceDisabled {
            get {
                return ResourceManager.GetString("RulesSequenceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence Reposition ENABLED.
        /// </summary>
        public static string RulesSequenceRepositionEnabled {
            get {
                return ResourceManager.GetString("RulesSequenceRepositionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence ENABLED, Threshold:.
        /// </summary>
        public static string RulesSequenceThreshold {
            get {
                return ResourceManager.GetString("RulesSequenceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Prints.
        /// </summary>
        public static string SavePrints {
            get {
                return ResourceManager.GetString("SavePrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan print.
        /// </summary>
        public static string ScanAgain {
            get {
                return ResourceManager.GetString("ScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan endorsement.
        /// </summary>
        public static string ScanEndorsement {
            get {
                return ResourceManager.GetString("ScanEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flat.
        /// </summary>
        public static string ScanKindFlat {
            get {
                return ResourceManager.GetString("ScanKindFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rolled.
        /// </summary>
        public static string ScanKindRolled {
            get {
                return ResourceManager.GetString("ScanKindRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scanner.
        /// </summary>
        public static string Scanner {
            get {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select finger for endorsement.
        /// </summary>
        public static string SelectEndorsement {
            get {
                return ResourceManager.GetString("SelectEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No match.
        /// </summary>
        public static string SequenceBad {
            get {
                return ResourceManager.GetString("SequenceBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence Check.
        /// </summary>
        public static string SequenceCheck {
            get {
                return ResourceManager.GetString("SequenceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when score is low.
        /// </summary>
        public static string SequenceErrorBadScore {
            get {
                return ResourceManager.GetString("SequenceErrorBadScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print matches.
        /// </summary>
        public static string SequenceGood {
            get {
                return ResourceManager.GetString("SequenceGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence :.
        /// </summary>
        public static string SequenceLabel {
            get {
                return ResourceManager.GetString("SequenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does not apply.
        /// </summary>
        public static string SequenceNA {
            get {
                return ResourceManager.GetString("SequenceNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence Options.
        /// </summary>
        public static string SequenceOptions {
            get {
                return ResourceManager.GetString("SequenceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can change print position.
        /// </summary>
        public static string SequencePosition {
            get {
                return ResourceManager.GetString("SequencePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partial Match.
        /// </summary>
        public static string SequenceScoreGood {
            get {
                return ResourceManager.GetString("SequenceScoreGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weak Match.
        /// </summary>
        public static string SequenceScoreLow {
            get {
                return ResourceManager.GetString("SequenceScoreLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Match.
        /// </summary>
        public static string SequenceScoreNone {
            get {
                return ResourceManager.GetString("SequenceScoreNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete Match.
        /// </summary>
        public static string SequenceScorePerfectMatch {
            get {
                return ResourceManager.GetString("SequenceScorePerfectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good Match.
        /// </summary>
        public static string SequenceScoreVeryGood {
            get {
                return ResourceManager.GetString("SequenceScoreVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very Weak Match.
        /// </summary>
        public static string SequenceScoreVeryLow {
            get {
                return ResourceManager.GetString("SequenceScoreVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence Threshold.
        /// </summary>
        public static string SequenceThreshold {
            get {
                return ResourceManager.GetString("SequenceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        public static string ServiceConnectedMessage {
            get {
                return ResourceManager.GetString("ServiceConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnected.
        /// </summary>
        public static string ServiceDisconnectedMessage {
            get {
                return ResourceManager.GetString("ServiceDisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation &apos;{0}&apos; failed..
        /// </summary>
        public static string ServiceOperationFailed {
            get {
                return ResourceManager.GetString("ServiceOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get Print Set.
        /// </summary>
        public static string ServiceOperationGetPrintSet {
            get {
                return ResourceManager.GetString("ServiceOperationGetPrintSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation could not be done on server side. See logs for details..
        /// </summary>
        public static string ServiceOperationNotCompleted {
            get {
                return ResourceManager.GetString("ServiceOperationNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Override.
        /// </summary>
        public static string ServiceOperationRemoveOverride {
            get {
                return ResourceManager.GetString("ServiceOperationRemoveOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set Override.
        /// </summary>
        public static string ServiceOperationSetOverride {
            get {
                return ResourceManager.GetString("ServiceOperationSetOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swap Prints.
        /// </summary>
        public static string ServiceOperationSwapPrints {
            get {
                return ResourceManager.GetString("ServiceOperationSwapPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set expected fingers.
        /// </summary>
        public static string SetExpectedFingers {
            get {
                return ResourceManager.GetString("SetExpectedFingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set finger.
        /// </summary>
        public static string SetFinger {
            get {
                return ResourceManager.GetString("SetFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        public static string ThresholdLabel {
            get {
                return ResourceManager.GetString("ThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold : {0}.
        /// </summary>
        public static string ThresholdScorePattern {
            get {
                return ResourceManager.GetString("ThresholdScorePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjust threshold level.
        /// </summary>
        public static string ThresholdTooltip {
            get {
                return ResourceManager.GetString("ThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Troubleshooting.
        /// </summary>
        public static string TroubleShooting {
            get {
                return ResourceManager.GetString("TroubleShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation :.
        /// </summary>
        public static string ValidationEnabledLabel {
            get {
                return ResourceManager.GetString("ValidationEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation.
        /// </summary>
        public static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This consent is to be used by a person applying for a position with a person or organization responsible for the well-being of one or more children or vulnerable persons, if the position is a position of authority or trust relative to those children or vulnerable persons and the applicant wishes to consent to a search being made in criminal conviction records to determine if the applicant has been convicted of a sexual offence listed in the schedule to the Criminal Records Act and has been pardoned or if th [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string VulnerableSectorConsent {
            get {
                return ResourceManager.GetString("VulnerableSectorConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vulnerable sector.
        /// </summary>
        public static string VulnerableSectorName {
            get {
                return ResourceManager.GetString("VulnerableSectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I understand that, as a result of giving this consent, if I am identified by fingerprint search as being the person named in a criminal record, including a criminal record for which one of the sexual offences listed in the schedule to the Criminal Records Act in respect of which a pardon was granted or issued, that record may be provided by the Commissioner of the Royal Canadian Mounted Police to the Minister of Public Safety and Emergency Preparedness, who may then disclose all or part of the information c [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string WaiverConsent {
            get {
                return ResourceManager.GetString("WaiverConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiver.
        /// </summary>
        public static string WaiverName {
            get {
                return ResourceManager.GetString("WaiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan again.
        /// </summary>
        public static string WizardActionScan {
            get {
                return ResourceManager.GetString("WizardActionScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply actions.
        /// </summary>
        public static string WizardApplyActions {
            get {
                return ResourceManager.GetString("WizardApplyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        public static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The reason must be specified. Only standard characters allowed..
        /// </summary>
        public static string WizardOtherReasonInvalid {
            get {
                return ResourceManager.GetString("WizardOtherReasonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        public static string WizardPrevious {
            get {
                return ResourceManager.GetString("WizardPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid print.
        /// </summary>
        public static string WizardPrintInvalid {
            get {
                return ResourceManager.GetString("WizardPrintInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print Ok.
        /// </summary>
        public static string WizardPrintOk {
            get {
                return ResourceManager.GetString("WizardPrintOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation failed.
        /// </summary>
        public static string WizardPrintWarning {
            get {
                return ResourceManager.GetString("WizardPrintWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When using the &apos;Other&apos; reason, you must enter the reason..
        /// </summary>
        public static string WizardReasonInvalid {
            get {
                return ResourceManager.GetString("WizardReasonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Review prints.
        /// </summary>
        public static string WizardReviewPrints {
            get {
                return ResourceManager.GetString("WizardReviewPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Review : There are some incorrect prints.
        /// </summary>
        public static string WizardReviewTitle {
            get {
                return ResourceManager.GetString("WizardReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show advanced information.
        /// </summary>
        public static string WizardShowAdvanced {
            get {
                return ResourceManager.GetString("WizardShowAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify reason.
        /// </summary>
        public static string WizardSpecifyReason {
            get {
                return ResourceManager.GetString("WizardSpecifyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à * Print was modified or a reason defined to ignore the current error..
        /// </summary>
        public static string WizardStarExplained {
            get {
                return ResourceManager.GetString("WizardStarExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Errors have been detected! Please rescan :.
        /// </summary>
        public static string WizardStatusCaptureAgain {
            get {
                return ResourceManager.GetString("WizardStatusCaptureAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By clicking &quot;Apply actions&quot;, all the prints will be added to your file..
        /// </summary>
        public static string WizardStatusEndCapture {
            get {
                return ResourceManager.GetString("WizardStatusEndCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to correct some prints before you continue.
        ///
        ///It is recommanded that you scan the prints again. 
        ///
        ///For advanced use, you may click on &quot;Review prints&quot;..
        /// </summary>
        public static string WizardStatusErrorList {
            get {
                return ResourceManager.GetString("WizardStatusErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All errors have been corrected..
        /// </summary>
        public static string WizardStatusNoError {
            get {
                return ResourceManager.GetString("WizardStatusNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detailed print information.
        /// </summary>
        public static string ZoomWindowTitle {
            get {
                return ResourceManager.GetString("ZoomWindowTitle", resourceCulture);
            }
        }
    }
}
