//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintsCapture.Ui.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintsCapture.Ui.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept *.
        /// </summary>
        public static string AcceptStar {
            get {
                return ResourceManager.GetString("AcceptStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print capture application.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Capture.
        /// </summary>
        public static string CaptureEnd {
            get {
                return ResourceManager.GetString("CaptureEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of errors, rescan or override prints. Press &quot;End&quot; when done..
        /// </summary>
        public static string CaptureEndInstruction {
            get {
                return ResourceManager.GetString("CaptureEndInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Endorsement Finger.
        /// </summary>
        public static string CaptureEndorsement {
            get {
                return ResourceManager.GetString("CaptureEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats only.
        /// </summary>
        public static string CaptureFlatOnly {
            get {
                return ResourceManager.GetString("CaptureFlatOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode.
        /// </summary>
        public static string CaptureMode {
            get {
                return ResourceManager.GetString("CaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats and rolled.
        /// </summary>
        public static string CaptureStandard14 {
            get {
                return ResourceManager.GetString("CaptureStandard14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats, rolled and palms.
        /// </summary>
        public static string CaptureStandardAndPalm {
            get {
                return ResourceManager.GetString("CaptureStandardAndPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string CaptureStart {
            get {
                return ResourceManager.GetString("CaptureStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag missing prints and press &quot;Scan&quot; button to start..
        /// </summary>
        public static string CaptureStartInstruction {
            get {
                return ResourceManager.GetString("CaptureStartInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardScan.
        /// </summary>
        public static string CardScan {
            get {
                return ResourceManager.GetString("CardScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string CloseApplicationTitle {
            get {
                return ResourceManager.GetString("CloseApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print session will end. No print will be saved..
        /// </summary>
        public static string CloseConfirmationPrompt {
            get {
                return ResourceManager.GetString("CloseConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression :.
        /// </summary>
        public static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Text.
        /// </summary>
        public static string ConsentText {
            get {
                return ResourceManager.GetString("ConsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue. Some errors must be corrected..
        /// </summary>
        public static string CorrectErrorBeforeContinue {
            get {
                return ResourceManager.GetString("CorrectErrorBeforeContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set device information on service..
        /// </summary>
        public static string CouldNotSetDeviceInformation {
            get {
                return ResourceManager.GetString("CouldNotSetDeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Device.
        /// </summary>
        public static string CurrentDevice {
            get {
                return ResourceManager.GetString("CurrentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data compression :.
        /// </summary>
        public static string DataCompressionLabel {
            get {
                return ResourceManager.GetString("DataCompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-mm-dd.
        /// </summary>
        public static string DateFormatHelper {
            get {
                return ResourceManager.GetString("DateFormatHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string DatePickerWatermark {
            get {
                return ResourceManager.GetString("DatePickerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define override.
        /// </summary>
        public static string DefineOverride {
            get {
                return ResourceManager.GetString("DefineOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dpi :.
        /// </summary>
        public static string DpiDescriptionLabel {
            get {
                return ResourceManager.GetString("DpiDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditPrint {
            get {
                return ResourceManager.GetString("EditPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sequence check.
        /// </summary>
        public static string EnableSequenceCheck {
            get {
                return ResourceManager.GetString("EnableSequenceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The print session will end. The prints will be saved..
        /// </summary>
        public static string EndConfirmationPrompt {
            get {
                return ResourceManager.GetString("EndConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the english endorsement text..
        /// </summary>
        public static string EndorsementConsentText {
            get {
                return ResourceManager.GetString("EndorsementConsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsement consent text for third party.
        /// </summary>
        public static string EndorsementConsentWindowTitle {
            get {
                return ResourceManager.GetString("EndorsementConsentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsement Finger.
        /// </summary>
        public static string EndorsementFinger {
            get {
                return ResourceManager.GetString("EndorsementFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string EndorsementNamePattern {
            get {
                return ResourceManager.GetString("EndorsementNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The print session will end. No endorsement finger was captured. The prints will be saved..
        /// </summary>
        public static string EndorsementNotSetPrompt {
            get {
                return ResourceManager.GetString("EndorsementNotSetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsement.
        /// </summary>
        public static string EndorsementTitle {
            get {
                return ResourceManager.GetString("EndorsementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand.
        /// </summary>
        public static string enumHandLeft {
            get {
                return ResourceManager.GetString("enumHandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string enumHandNone {
            get {
                return ResourceManager.GetString("enumHandNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Palm.
        /// </summary>
        public static string enumHandPartCompletePalm {
            get {
                return ResourceManager.GetString("enumHandPartCompletePalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsement.
        /// </summary>
        public static string enumHandPartEndorsement {
            get {
                return ResourceManager.GetString("enumHandPartEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Fingers.
        /// </summary>
        public static string enumHandPartFourFlats {
            get {
                return ResourceManager.GetString("enumHandPartFourFlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothenar.
        /// </summary>
        public static string enumHandPartHypothenar {
            get {
                return ResourceManager.GetString("enumHandPartHypothenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string enumHandPartIndex {
            get {
                return ResourceManager.GetString("enumHandPartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little.
        /// </summary>
        public static string enumHandPartLittle {
            get {
                return ResourceManager.GetString("enumHandPartLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Palm.
        /// </summary>
        public static string enumHandPartLowerPalm {
            get {
                return ResourceManager.GetString("enumHandPartLowerPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string enumHandPartMiddle {
            get {
                return ResourceManager.GetString("enumHandPartMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        public static string enumHandPartRing {
            get {
                return ResourceManager.GetString("enumHandPartRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb.
        /// </summary>
        public static string enumHandPartThumb {
            get {
                return ResourceManager.GetString("enumHandPartThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Thumbs.
        /// </summary>
        public static string enumHandPartTwoThumbs {
            get {
                return ResourceManager.GetString("enumHandPartTwoThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperPalm.
        /// </summary>
        public static string enumHandPartUpperPalm {
            get {
                return ResourceManager.GetString("enumHandPartUpperPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand.
        /// </summary>
        public static string enumHandRight {
            get {
                return ResourceManager.GetString("enumHandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string enumHandScanKindFlat {
            get {
                return ResourceManager.GetString("enumHandScanKindFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled.
        /// </summary>
        public static string enumHandScanKindRolled {
            get {
                return ResourceManager.GetString("enumHandScanKindRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) have been detected. Please rescan :.
        /// </summary>
        public static string ErrorHaveBeenDetected {
            get {
                return ResourceManager.GetString("ErrorHaveBeenDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Presence.
        /// </summary>
        public static string FingerPresenceWindowTitle {
            get {
                return ResourceManager.GetString("FingerPresenceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingers.
        /// </summary>
        public static string Fingers {
            get {
                return ResourceManager.GetString("Fingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Fingers.
        /// </summary>
        public static string FourFinger {
            get {
                return ResourceManager.GetString("FourFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandaged.
        /// </summary>
        public static string HandPartBandaged {
            get {
                return ResourceManager.GetString("HandPartBandaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Reason.
        /// </summary>
        public static string HandPartForeignReason {
            get {
                return ResourceManager.GetString("HandPartForeignReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Image.
        /// </summary>
        public static string HandPartMissingImage {
            get {
                return ResourceManager.GetString("HandPartMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Limitations.
        /// </summary>
        public static string HandPartPhysicalLimitation {
            get {
                return ResourceManager.GetString("HandPartPhysicalLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string HandPartPresent {
            get {
                return ResourceManager.GetString("HandPartPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amputated.
        /// </summary>
        public static string HandPatAmputated {
            get {
                return ResourceManager.GetString("HandPatAmputated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include palm prints.
        /// </summary>
        public static string IncludePalm {
            get {
                return ResourceManager.GetString("IncludePalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text contains invalid characters.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Preview Window.
        /// </summary>
        public static string LivePreviewTitle {
            get {
                return ResourceManager.GetString("LivePreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveScan.
        /// </summary>
        public static string Livescan {
            get {
                return ResourceManager.GetString("Livescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading previous prints. Please wait..
        /// </summary>
        public static string LoadingPreviousPrints {
            get {
                return ResourceManager.GetString("LoadingPreviousPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading prints {0} of {1}.
        /// </summary>
        public static string LoadingPrintsXOfY {
            get {
                return ResourceManager.GetString("LoadingPrintsXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string MiscOptions {
            get {
                return ResourceManager.GetString("MiscOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the missing finger finger contain at least the year and the month..
        /// </summary>
        public static string MissingDateInvalidLenght {
            get {
                return ResourceManager.GetString("MissingDateInvalidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing finger.
        /// </summary>
        public static string MissingFinger {
            get {
                return ResourceManager.GetString("MissingFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing since.
        /// </summary>
        public static string MissingSince {
            get {
                return ResourceManager.GetString("MissingSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print override or missing attribute different on server for {0}..
        /// </summary>
        public static string MsgPrintSyncError {
            get {
                return ResourceManager.GetString("MsgPrintSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print position differs for {0}. Desactivate the position and reactivate it again..
        /// </summary>
        public static string MsgSwapDifferent {
            get {
                return ResourceManager.GetString("MsgSwapDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression into Wsq failed for {0}. Resend the print..
        /// </summary>
        public static string MsgWsqCompressionFailed {
            get {
                return ResourceManager.GetString("MsgWsqCompressionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device.
        /// </summary>
        public static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No override.
        /// </summary>
        public static string NoOverride {
            get {
                return ResourceManager.GetString("NoOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No print.
        /// </summary>
        public static string NoPrint {
            get {
                return ResourceManager.GetString("NoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print analyse in progress ....
        /// </summary>
        public static string OperationAnalysis {
            get {
                return ResourceManager.GetString("OperationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print analysis completed.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No print to analyse.
        /// </summary>
        public static string OperationNoPrint {
            get {
                return ResourceManager.GetString("OperationNoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override options always visible.
        /// </summary>
        public static string OverrideAlwayDisplayed {
            get {
                return ResourceManager.GetString("OverrideAlwayDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable override of flat prints.
        /// </summary>
        public static string OverrideDisableFlat {
            get {
                return ResourceManager.GetString("OverrideDisableFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable override of palm prints.
        /// </summary>
        public static string OverrideDisablePalm {
            get {
                return ResourceManager.GetString("OverrideDisablePalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable override of rolled prints.
        /// </summary>
        public static string OverrideDisableRolled {
            get {
                return ResourceManager.GetString("OverrideDisableRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats :.
        /// </summary>
        public static string OverrideFlatLabel {
            get {
                return ResourceManager.GetString("OverrideFlatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override reason cannot be blank. Specify a reason..
        /// </summary>
        public static string OverrideReasonCannotBeBlank {
            get {
                return ResourceManager.GetString("OverrideReasonCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry :.
        /// </summary>
        public static string OverrideRetryNeededLabel {
            get {
                return ResourceManager.GetString("OverrideRetryNeededLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled :.
        /// </summary>
        public static string OverrideRolledLabel {
            get {
                return ResourceManager.GetString("OverrideRolledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides.
        /// </summary>
        public static string Overrides {
            get {
                return ResourceManager.GetString("Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palm Quality Control.
        /// </summary>
        public static string PalmQualityControlTitle {
            get {
                return ResourceManager.GetString("PalmQualityControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palms.
        /// </summary>
        public static string Palms {
            get {
                return ResourceManager.GetString("Palms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string PhysicalPartNamePattern {
            get {
                return ResourceManager.GetString("PhysicalPartNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original scanned position was {0}.
        /// </summary>
        public static string PositionChangedFrom {
            get {
                return ResourceManager.GetString("PositionChangedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position attribution :.
        /// </summary>
        public static string PositionEnabledLabel {
            get {
                return ResourceManager.GetString("PositionEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence / Presence.
        /// </summary>
        public static string PresenceWindowTitle {
            get {
                return ResourceManager.GetString("PresenceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous print.
        /// </summary>
        public static string PreviousPrint {
            get {
                return ResourceManager.GetString("PreviousPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string PrintFingerIndex {
            get {
                return ResourceManager.GetString("PrintFingerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little.
        /// </summary>
        public static string PrintFingerLittle {
            get {
                return ResourceManager.GetString("PrintFingerLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string PrintFingerMiddle {
            get {
                return ResourceManager.GetString("PrintFingerMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        public static string PrintFingerRing {
            get {
                return ResourceManager.GetString("PrintFingerRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb.
        /// </summary>
        public static string PrintFingerThumb {
            get {
                return ResourceManager.GetString("PrintFingerThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string PrintFlat {
            get {
                return ResourceManager.GetString("PrintFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on image to shrink it&apos;s size..
        /// </summary>
        public static string PrintIsZoomed {
            get {
                return ResourceManager.GetString("PrintIsZoomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Prints.
        /// </summary>
        public static string PrintLeftHand {
            get {
                return ResourceManager.GetString("PrintLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print could match to {0}. Sequence : {1}.
        /// </summary>
        public static string PrintMatchWarning {
            get {
                return ResourceManager.GetString("PrintMatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}), {2}.
        /// </summary>
        public static string PrintNamePattern {
            get {
                return ResourceManager.GetString("PrintNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palm.
        /// </summary>
        public static string PrintPalm {
            get {
                return ResourceManager.GetString("PrintPalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothenar.
        /// </summary>
        public static string PrintPalmHypothenar {
            get {
                return ResourceManager.GetString("PrintPalmHypothenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Palm.
        /// </summary>
        public static string PrintPalmLower {
            get {
                return ResourceManager.GetString("PrintPalmLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Palm.
        /// </summary>
        public static string PrintPalmUpper {
            get {
                return ResourceManager.GetString("PrintPalmUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print position was changed to {0}.
        /// </summary>
        public static string PrintPositionChangedTo {
            get {
                return ResourceManager.GetString("PrintPositionChangedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string PrintQualityBad {
            get {
                return ResourceManager.GetString("PrintQualityBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string PrintQualityExcellent {
            get {
                return ResourceManager.GetString("PrintQualityExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string PrintQualityGood {
            get {
                return ResourceManager.GetString("PrintQualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Bad.
        /// </summary>
        public static string PrintQualityVeryBad {
            get {
                return ResourceManager.GetString("PrintQualityVeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string PrintQualityVeryGood {
            get {
                return ResourceManager.GetString("PrintQualityVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Prints.
        /// </summary>
        public static string PrintRightHand {
            get {
                return ResourceManager.GetString("PrintRightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled.
        /// </summary>
        public static string PrintRolled {
            get {
                return ResourceManager.GetString("PrintRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print parts.
        /// </summary>
        public static string PrintSegments {
            get {
                return ResourceManager.GetString("PrintSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Session.
        /// </summary>
        public static string PrintSession {
            get {
                return ResourceManager.GetString("PrintSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some prints are not ready :.
        /// </summary>
        public static string PrintsNotReady {
            get {
                return ResourceManager.GetString("PrintsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PrintsStatusOk {
            get {
                return ResourceManager.GetString("PrintsStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print captured more than once..
        /// </summary>
        public static string PrintStatusDouble {
            get {
                return ResourceManager.GetString("PrintStatusDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In error.
        /// </summary>
        public static string PrintStatusInError {
            get {
                return ResourceManager.GetString("PrintStatusInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In error and print position was changed.
        /// </summary>
        public static string PrintStatusInErrorSwapped {
            get {
                return ResourceManager.GetString("PrintStatusInErrorSwapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print is being processed.
        /// </summary>
        public static string PrintStatusInProcess {
            get {
                return ResourceManager.GetString("PrintStatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print is missing.
        /// </summary>
        public static string PrintStatusMissing {
            get {
                return ResourceManager.GetString("PrintStatusMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print not captured.
        /// </summary>
        public static string PrintStatusNotCaptured {
            get {
                return ResourceManager.GetString("PrintStatusNotCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print error was overriden.
        /// </summary>
        public static string PrintStatusOverriden {
            get {
                return ResourceManager.GetString("PrintStatusOverriden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending evaluation.
        /// </summary>
        public static string PrintStatusPendingEvaluation {
            get {
                return ResourceManager.GetString("PrintStatusPendingEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print is ready.
        /// </summary>
        public static string PrintStatusProcessed {
            get {
                return ResourceManager.GetString("PrintStatusProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print quality is bad.
        /// </summary>
        public static string PrintStatusQualityError {
            get {
                return ResourceManager.GetString("PrintStatusQualityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Sequence check failed.
        /// </summary>
        public static string PrintStatusSequenceError {
            get {
                return ResourceManager.GetString("PrintStatusSequenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence score was matched to another finger..
        /// </summary>
        public static string PrintStatusSequenceSwappedError {
            get {
                return ResourceManager.GetString("PrintStatusSequenceSwappedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service error.
        /// </summary>
        public static string PrintStatusServiceError {
            get {
                return ResourceManager.GetString("PrintStatusServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string PrintStatusSubmited {
            get {
                return ResourceManager.GetString("PrintStatusSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template in error.
        /// </summary>
        public static string PrintStatusTemplateError {
            get {
                return ResourceManager.GetString("PrintStatusTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PrintStatusUnknown {
            get {
                return ResourceManager.GetString("PrintStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string PrintStatusUnknownError {
            get {
                return ResourceManager.GetString("PrintStatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated, but print position was changed.
        /// </summary>
        public static string PrintStatusValidatedSwapped {
            get {
                return ResourceManager.GetString("PrintStatusValidatedSwapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print was matched to : {0}.
        /// </summary>
        public static string PrintWasMatchedTo {
            get {
                return ResourceManager.GetString("PrintWasMatchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad quality.
        /// </summary>
        public static string QualityBad {
            get {
                return ResourceManager.GetString("QualityBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality was evaluated.
        /// </summary>
        public static string QualityEvaluated {
            get {
                return ResourceManager.GetString("QualityEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good quality.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string QualityLabel {
            get {
                return ResourceManager.GetString("QualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality : {0}.
        /// </summary>
        public static string QualityScorePattern {
            get {
                return ResourceManager.GetString("QualityScorePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality threshold.
        /// </summary>
        public static string QualityThreshold {
            get {
                return ResourceManager.GetString("QualityThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reposition.
        /// </summary>
        public static string Reposition {
            get {
                return ResourceManager.GetString("Reposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Service.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session and all prints will be reseted..
        /// </summary>
        public static string ResetConfirmationPrompt {
            get {
                return ResourceManager.GetString("ResetConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution : {0}.
        /// </summary>
        public static string ResolutionInfo {
            get {
                return ResourceManager.GetString("ResolutionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution :.
        /// </summary>
        public static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Resolution for fingerprints. Configure correctly and try again..
        /// </summary>
        public static string ResolutionNotSet {
            get {
                return ResourceManager.GetString("ResolutionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolutions.
        /// </summary>
        public static string Resolutions {
            get {
                return ResourceManager.GetString("Resolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Service.
        /// </summary>
        public static string RestartService {
            get {
                return ResourceManager.GetString("RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Capture.
        /// </summary>
        public static string ResumeCapture {
            get {
                return ResourceManager.GetString("ResumeCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Prints.
        /// </summary>
        public static string SavePrints {
            get {
                return ResourceManager.GetString("SavePrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan print.
        /// </summary>
        public static string ScanAgain {
            get {
                return ResourceManager.GetString("ScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan endorsement.
        /// </summary>
        public static string ScanEndorsement {
            get {
                return ResourceManager.GetString("ScanEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string ScanKindFlat {
            get {
                return ResourceManager.GetString("ScanKindFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled.
        /// </summary>
        public static string ScanKindRolled {
            get {
                return ResourceManager.GetString("ScanKindRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string Scanner {
            get {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select finger for endorsement.
        /// </summary>
        public static string SelectEndorsement {
            get {
                return ResourceManager.GetString("SelectEndorsement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match.
        /// </summary>
        public static string SequenceBad {
            get {
                return ResourceManager.GetString("SequenceBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Check.
        /// </summary>
        public static string SequenceCheck {
            get {
                return ResourceManager.GetString("SequenceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when score is low.
        /// </summary>
        public static string SequenceErrorBadScore {
            get {
                return ResourceManager.GetString("SequenceErrorBadScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print matches.
        /// </summary>
        public static string SequenceGood {
            get {
                return ResourceManager.GetString("SequenceGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence :.
        /// </summary>
        public static string SequenceLabel {
            get {
                return ResourceManager.GetString("SequenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not apply.
        /// </summary>
        public static string SequenceNA {
            get {
                return ResourceManager.GetString("SequenceNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Options.
        /// </summary>
        public static string SequenceOptions {
            get {
                return ResourceManager.GetString("SequenceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can change print position.
        /// </summary>
        public static string SequencePosition {
            get {
                return ResourceManager.GetString("SequencePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Match.
        /// </summary>
        public static string SequenceScoreGood {
            get {
                return ResourceManager.GetString("SequenceScoreGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Match.
        /// </summary>
        public static string SequenceScoreLow {
            get {
                return ResourceManager.GetString("SequenceScoreLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        public static string SequenceScoreNone {
            get {
                return ResourceManager.GetString("SequenceScoreNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Match.
        /// </summary>
        public static string SequenceScorePerfectMatch {
            get {
                return ResourceManager.GetString("SequenceScorePerfectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Match.
        /// </summary>
        public static string SequenceScoreVeryGood {
            get {
                return ResourceManager.GetString("SequenceScoreVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Weak Match.
        /// </summary>
        public static string SequenceScoreVeryLow {
            get {
                return ResourceManager.GetString("SequenceScoreVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Threshold.
        /// </summary>
        public static string SequenceThreshold {
            get {
                return ResourceManager.GetString("SequenceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ServiceConnectedMessage {
            get {
                return ResourceManager.GetString("ServiceConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string ServiceDisconnectedMessage {
            get {
                return ResourceManager.GetString("ServiceDisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; failed..
        /// </summary>
        public static string ServiceOperationFailed {
            get {
                return ResourceManager.GetString("ServiceOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Print Set.
        /// </summary>
        public static string ServiceOperationGetPrintSet {
            get {
                return ResourceManager.GetString("ServiceOperationGetPrintSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation could not be done on server side. See logs for details..
        /// </summary>
        public static string ServiceOperationNotCompleted {
            get {
                return ResourceManager.GetString("ServiceOperationNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Override.
        /// </summary>
        public static string ServiceOperationRemoveOverride {
            get {
                return ResourceManager.GetString("ServiceOperationRemoveOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Override.
        /// </summary>
        public static string ServiceOperationSetOverride {
            get {
                return ResourceManager.GetString("ServiceOperationSetOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Prints.
        /// </summary>
        public static string ServiceOperationSwapPrints {
            get {
                return ResourceManager.GetString("ServiceOperationSwapPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set expected fingers.
        /// </summary>
        public static string SetExpectedFingers {
            get {
                return ResourceManager.GetString("SetExpectedFingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set finger.
        /// </summary>
        public static string SetFinger {
            get {
                return ResourceManager.GetString("SetFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string ThresholdLabel {
            get {
                return ResourceManager.GetString("ThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold : {0}.
        /// </summary>
        public static string ThresholdScorePattern {
            get {
                return ResourceManager.GetString("ThresholdScorePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust threshold level.
        /// </summary>
        public static string ThresholdTooltip {
            get {
                return ResourceManager.GetString("ThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting.
        /// </summary>
        public static string TroubleShooting {
            get {
                return ResourceManager.GetString("TroubleShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation :.
        /// </summary>
        public static string ValidationEnabledLabel {
            get {
                return ResourceManager.GetString("ValidationEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This consent is to be used by a person applying for a position with a person or organization responsible for the well-being of one or more children or vulnerable persons, if the position is a position of authority or trust relative to those children or vulnerable persons and the applicant wishes to consent to a search being made in criminal conviction records to determine if the applicant has been convicted of a sexual offence listed in the schedule to the Criminal Records Act and has been pardoned or if th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VulnerableSectorConsent {
            get {
                return ResourceManager.GetString("VulnerableSectorConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerable sector.
        /// </summary>
        public static string VulnerableSectorName {
            get {
                return ResourceManager.GetString("VulnerableSectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that, as a result of giving this consent, if I am identified by fingerprint search as being the person named in a criminal record, including a criminal record for which one of the sexual offences listed in the schedule to the Criminal Records Act in respect of which a pardon was granted or issued, that record may be provided by the Commissioner of the Royal Canadian Mounted Police to the Minister of Public Safety and Emergency Preparedness, who may then disclose all or part of the information c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WaiverConsent {
            get {
                return ResourceManager.GetString("WaiverConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiver.
        /// </summary>
        public static string WaiverName {
            get {
                return ResourceManager.GetString("WaiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again.
        /// </summary>
        public static string WizardActionScan {
            get {
                return ResourceManager.GetString("WizardActionScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply actions.
        /// </summary>
        public static string WizardApplyActions {
            get {
                return ResourceManager.GetString("WizardApplyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason must be specified. Only standard characters allowed..
        /// </summary>
        public static string WizardOtherReasonInvalid {
            get {
                return ResourceManager.GetString("WizardOtherReasonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string WizardPrevious {
            get {
                return ResourceManager.GetString("WizardPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid print.
        /// </summary>
        public static string WizardPrintInvalid {
            get {
                return ResourceManager.GetString("WizardPrintInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Ok.
        /// </summary>
        public static string WizardPrintOk {
            get {
                return ResourceManager.GetString("WizardPrintOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string WizardPrintWarning {
            get {
                return ResourceManager.GetString("WizardPrintWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using the &apos;Other&apos; reason, you must enter the reason..
        /// </summary>
        public static string WizardReasonInvalid {
            get {
                return ResourceManager.GetString("WizardReasonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review prints.
        /// </summary>
        public static string WizardReviewPrints {
            get {
                return ResourceManager.GetString("WizardReviewPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review : There are some incorrect prints.
        /// </summary>
        public static string WizardReviewTitle {
            get {
                return ResourceManager.GetString("WizardReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show advanced information.
        /// </summary>
        public static string WizardShowAdvanced {
            get {
                return ResourceManager.GetString("WizardShowAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify reason.
        /// </summary>
        public static string WizardSpecifyReason {
            get {
                return ResourceManager.GetString("WizardSpecifyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Print was modified or a reason defined to ignore the current error..
        /// </summary>
        public static string WizardStarExplained {
            get {
                return ResourceManager.GetString("WizardStarExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors have been detected! Please rescan :.
        /// </summary>
        public static string WizardStatusCaptureAgain {
            get {
                return ResourceManager.GetString("WizardStatusCaptureAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Apply actions&quot;, all the prints will be added to your file..
        /// </summary>
        public static string WizardStatusEndCapture {
            get {
                return ResourceManager.GetString("WizardStatusEndCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to correct some prints before you continue.
        ///
        ///It is recommanded that you scan the prints again. 
        ///
        ///For advanced use, you may click on &quot;Review prints&quot;..
        /// </summary>
        public static string WizardStatusErrorList {
            get {
                return ResourceManager.GetString("WizardStatusErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All errors have been corrected..
        /// </summary>
        public static string WizardStatusNoError {
            get {
                return ResourceManager.GetString("WizardStatusNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed print information.
        /// </summary>
        public static string ZoomWindowTitle {
            get {
                return ResourceManager.GetString("ZoomWindowTitle", resourceCulture);
            }
        }
    }
}
